server:
  port: 8884
  address: 0.0.0.0

spring:
  application:
    name: product-service
#  cloud:
#    nacos:
#      discovery:
#          server-addr: 127.0.0.1:8848


springCloud-test:
  ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true