spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: open
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix= 2
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true