server:
  port: 8885
  address: 0.0.0.0

spring:
  application:
    name: order-service
#  cloud:
#    nacos:
#      discovery:
#          server-addr: 127.0.0.1:8848
  #************H2  Begin*************
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9090/mem:sleuth
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
#************H2  end****************








springCloud-test:
  ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true